### ISSUE TITLE
import 报错

### ISSUE THREAD

**Issue by janglichao** [OpenBMB/BMTrain#102]
torch 2.0.1+cu117
ubuntu22
安装bmtrain成功，import报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kidd/anaconda3/envs/cpmbee/lib/python3.8/site-packages/bmtrain/__init__.py", line 2, in <module>
    from .init import init_distributed
  File "/home/kidd/anaconda3/envs/cpmbee/lib/python3.8/site-packages/bmtrain/init.py", line 8, in <module>
    from . import nccl
  File "/home/kidd/anaconda3/envs/cpmbee/lib/python3.8/site-packages/bmtrain/nccl/__init__.py", line 4, in <module>
    from . import _C as C
ImportError: /home/kidd/anaconda3/envs/cpmbee/lib/python3.8/site-packages/bmtrain/nccl/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: ncclBroadcast

**Comment by Achazwl** [comment]
torch>=2.0 is not yet supported.

**Comment by janglichao** [comment]
> torch>=2.0 is not yet supported.

I switched to torch1.9.1 still report this error

**Comment by Achazwl** [comment]
try pip install bmtrain with extra flag `--no-cache-dir`. torch 1.10~1.13 is preferred.

**Comment by Achazwl** [comment]
`pip uninstall bmtrain` and then `pip install bmtrain --no-cache-dir`.

**Comment by qiezikuangge** [comment]
解决了吗

**Comment by Achazwl** [comment]
Torch >= 2.0 is now supported. (since PR #115 )
