### ISSUE TITLE
windows 安装失败

### ISSUE THREAD

**Issue by wilderchen** [OpenBMB/BMTrain#107]
```
nvcc -v
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

```
pip install bmtrain --no-cache-dir
```

 Building wheel for bmtrain (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      E:\virtualenvs\cpmbee\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\block_layer.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\checkpointing.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\debug.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\global_var.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\init.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\layer.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\parameter.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\param_init.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\pipe_layer.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\store.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\synchronize.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\utils.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\wrapper.py -> build\lib.win-amd64-cpython-310\bmtrain
      copying bmtrain\__init__.py -> build\lib.win-amd64-cpython-310\bmtrain
      creating build\lib.win-amd64-cpython-310\bmtrain\benchmark
      copying bmtrain\benchmark\all_gather.py -> build\lib.win-amd64-cpython-310\bmtrain\benchmark
      copying bmtrain\benchmark\reduce_scatter.py -> build\lib.win-amd64-cpython-310\bmtrain\benchmark
      copying bmtrain\benchmark\send_recv.py -> build\lib.win-amd64-cpython-310\bmtrain\benchmark
      copying bmtrain\benchmark\shape.py -> build\lib.win-amd64-cpython-310\bmtrain\benchmark
      copying bmtrain\benchmark\utils.py -> build\lib.win-amd64-cpython-310\bmtrain\benchmark
      copying bmtrain\benchmark\__init__.py -> build\lib.win-amd64-cpython-310\bmtrain\benchmark
      creating build\lib.win-amd64-cpython-310\bmtrain\distributed
      copying bmtrain\distributed\ops.py -> build\lib.win-amd64-cpython-310\bmtrain\distributed
      copying bmtrain\distributed\__init__.py -> build\lib.win-amd64-cpython-310\bmtrain\distributed
      creating build\lib.win-amd64-cpython-310\bmtrain\inspect
      copying bmtrain\inspect\format.py -> build\lib.win-amd64-cpython-310\bmtrain\inspect
      copying bmtrain\inspect\model.py -> build\lib.win-amd64-cpython-310\bmtrain\inspect
      copying bmtrain\inspect\tensor.py -> build\lib.win-amd64-cpython-310\bmtrain\inspect
      copying bmtrain\inspect\__init__.py -> build\lib.win-amd64-cpython-310\bmtrain\inspect
      creating build\lib.win-amd64-cpython-310\bmtrain\loss
      copying bmtrain\loss\cross_entropy.py -> build\lib.win-amd64-cpython-310\bmtrain\loss
      copying bmtrain\loss\__init__.py -> build\lib.win-amd64-cpython-310\bmtrain\loss
      creating build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      copying bmtrain\lr_scheduler\cosine.py -> build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      copying bmtrain\lr_scheduler\exponential.py -> build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      copying bmtrain\lr_scheduler\linear.py -> build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      copying bmtrain\lr_scheduler\noam.py -> build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      copying bmtrain\lr_scheduler\no_decay.py -> build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      copying bmtrain\lr_scheduler\warmup.py -> build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      copying bmtrain\lr_scheduler\__init__.py -> build\lib.win-amd64-cpython-310\bmtrain\lr_scheduler
      creating build\lib.win-amd64-cpython-310\bmtrain\nccl
      copying bmtrain\nccl\enums.py -> build\lib.win-amd64-cpython-310\bmtrain\nccl
      copying bmtrain\nccl\__init__.py -> build\lib.win-amd64-cpython-310\bmtrain\nccl
      creating build\lib.win-amd64-cpython-310\bmtrain\optim
      copying bmtrain\optim\adam.py -> build\lib.win-amd64-cpython-310\bmtrain\optim
      copying bmtrain\optim\adam_offload.py -> build\lib.win-amd64-cpython-310\bmtrain\optim
      copying bmtrain\optim\optim_manager.py -> build\lib.win-amd64-cpython-310\bmtrain\optim
      E:\virtualenvs\cpmbee\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-txskv6c2\bmtrain_c1bb9dd57e27434ba3ec6faa2435cbfe\setup.py", line 74, in <module>
          setup(
          return distutils.core.setup(**attrs)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\virtualenvs\cpmbee\lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "E:\virtualenvs\cpmbee\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "E:\virtualenvs\cpmbee\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "E:\virtualenvs\cpmbee\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "E:\virtualenvs\cpmbee\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "E:\virtualenvs\cpmbee\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 195, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bmtrain
  Running setup.py clean for bmtrain
Failed to build bmtrain
ERROR: Could not build wheels for bmtrain, which is required to install pyproject.toml-based projects

**Comment by wangnan229** [comment]
同问

**Comment by MayDomine** [comment]
Windows 目前在适配中，敬请期待
