### ISSUE TITLE
安装成功，但是导入失败， 无法从 bmtrain.nccl 中导入 'C_' 

### ISSUE THREAD

**Issue by YingLaiLin** [OpenBMB/BMTrain#113]
torch 版本为: 1.12.0+cu116
gcc: 7.5.0
报错信息：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ms_test1/lyl/CPM-Live/BMTrain-main/bmtrain/__init__.py", line 2, in <module>
    from .init import init_distributed
  File "/ms_test1/lyl/CPM-Live/BMTrain-main/bmtrain/init.py", line 8, in <module>
    from . import nccl
  File "/ms_test1/lyl/CPM-Live/BMTrain-main/bmtrain/nccl/__init__.py", line 4, in <module>
    from . import _C as C
ImportError: cannot import name '_C' from 'bmtrain.nccl' (/ms_test1/lyl/CPM-Live/BMTrain-main/bmtrain/nccl/__init__.py)

**Comment by Achazwl** [comment]
换一个目录再 import 试试，这个报错疑似是你在安装目录下执行 import

**Comment by YingLaiLin** [comment]
哦 好像是这个问题，我切换到其他目录就可以了。。 一开始报错的时候是 undefined symbol: _ZN2at4_ops9new_zeros4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEENS5_8optionalINS5_10ScalarTypeEEENS9_INS5_6LayoutEEENS9_INS5_6DeviceEEENS9_IbEE ，所以用源码安装，后面发现可以用 --no-cache-dir 的问题解决。
