### ISSUE TITLE
安装成功，但import失败，bmtrain版本0.2.2

### ISSUE THREAD

**Issue by Mandy0016** [OpenBMB/BMTrain#117]
具体报错信息：
```shell
>>> import bmtrain as bmt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/FlagAI/examples/Aquila/Aquila-chat/BMTrain/bmtrain/__init__.py", line 2, in <module>
    from .init import init_distributed
  File "/FlagAI/examples/Aquila/Aquila-chat/BMTrain/bmtrain/init.py", line 8, in <module>
    from . import nccl
  File "/FlagAI/examples/Aquila/Aquila-chat/BMTrain/bmtrain/nccl/__init__.py", line 4, in <module>
    from . import _C as C
ImportError: cannot import name '_C' from partially initialized module 'bmtrain.nccl' (most likely due to a circular import) 
```
环境信息：python3.10，torch1.13，cuda116，Ubuntu18.04

**Comment by Mandy0016** [comment]
重新install一下遇到了下面这个问题：
```shell
>>> import bmtrain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/LLM/baosiyu/FlagAI/examples/Aquila/Aquila-chat/BMTrain/bmtrain/__init__.py", line 2, in <module>
    from .init import init_distributed
  File "/LLM/baosiyu/FlagAI/examples/Aquila/Aquila-chat/BMTrain/bmtrain/init.py", line 8, in <module>
    from . import nccl
  File "/LLM/baosiyu/FlagAI/examples/Aquila/Aquila-chat/BMTrain/bmtrain/nccl/__init__.py", line 4, in <module>
    from . import _C as C
ImportError: /LLM/baosiyu/FlagAI/examples/Aquila/Aquila-chat/BMTrain/bmtrain/nccl/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: ncclBroadcast
```

**Comment by Achazwl** [comment]
cd 到 bmtrain 源码安装目录之外的目录去执行 import bmtrain，不能在安装路径下 import；
重装的时候增加安装参数 `--no-cache-dir`
