### ISSUE TITLE
RuntimeError: NCCL Error: unhandled cuda error

### ISSUE THREAD

**Issue by Kunlun-Zhu** [OpenBMB/BMTrain#20]
When I tried to use bmt.init_distributed(seed=0), I met the following problem.
````
Traceback (most recent call last):

  File "train_inner.py", line 19, in main
    bmt.init_distributed(seed=0)
  
File "/python3.9/site-packages/bmtrain/init.py", line 88, in init_distributed
    config['comm'] = nccl.commInitRank(unique_id, world_size, rank)
  
File "//python3.9/site-packages/bmtrain/nccl/__init__.py", line 77, in commInitRank
    return NCCLCommunicator(C.ncclCommInitRank(unique_id, world_size, rank))
````

Any idea why would this occur? Or how may I solve this problem? Thanks.

``
torchrun --nnodes=1 --nproc_per_node=8 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost train.py
``
This is how I run the program.

**Comment by a710128** [comment]
Is there a more detailed error message?

**Comment by Kunlun-Zhu** [comment]
Yeah there is an appendix Error, but I am not sure if this would be helpful.

````
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 674947) of binary: 
/home//bin/python
Traceback (most recent call last):
  File "/home/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.11.0', 'console_scripts', 'torchrun')())
  File "/home/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/lib/python3.9/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
````
Other than this, I was using wandb for recording, I am not sure if this would be an issue.
Thanks

**Comment by Kunlun-Zhu** [comment]
> Is there a more detailed error message?

Yeah there is an appendix Error, but I am not sure if this would be helpful.

````
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 3 (pid: 674947) of binary: 
/home//bin/python
Traceback (most recent call last):
  File "/home/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.11.0', 'console_scripts', 'torchrun')())
  File "/home/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/lib/python3.9/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
````
Other than this, I was using wandb for recording, I am not sure if this would be an issue.
And the cuda version is 11.1
Thanks

**Comment by a710128** [comment]
What about the Pytorch version?
`python3 -c "import torch;print(torch.version.cuda)"`

**Comment by Kunlun-Zhu** [comment]
> What about the Pytorch's cuda version? `python3 -c "import torch;print(torch.version.cuda)"`
``
11.3
``
The torch is functioning fine in other program, would this be a mismatch problem?

**Comment by a710128** [comment]
I guess that should be the case. I've received similar feedback before.

**Comment by a710128** [comment]
Pytorch 1.10 supports CUDA 11.1 and can be installed by `pip install torch==1.10.2+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html`.

**Comment by Kunlun-Zhu** [comment]
> Pytorch 1.10 supports CUDA 11.1 and can be installed by `pip install torch==1.10.2+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html`.

Thanks, this no longer is the issue.
