### ISSUE TITLE
TypeError: object of type 'TransformerBlockList' has no len()

### ISSUE THREAD

**Issue by etale-cohomology** [OpenBMB/BMTrain#65]
I'm trying to run [EleutherAI/gpt-j-6B](https://huggingface.co/EleutherAI/gpt-j-6B) on a Titan V (12 GB), which can't fit the weights, so after loading the PyTorch model I'm doing:

```
torch.cuda.device(0):  model = bminf.wrapper(model)
```

but, now I get the error (full error log at the end):

```
TypeError: object of type 'TransformerBlockList' has no len()
```

So I tried patching `class TransformerBlockList(torch.nn.Module)` by adding a `__len__`   method:

```
    def __len__(self):
        return len(self.layers)
```

and the model finally runs, but I'm getting nonsense (random words) as output.

The code is roughly:

```
import transformers

model = transformers.GPTJForCausalLM.from_pretrained(f'EleutherAI/{MODELN}', revision='float16', torch_dtype=torch.float16, low_cpu_mem_usage=True)
torch.save(model, MODELN)
print(model)

if not os.path.exists(f'{DATAD}/{MODELN}.pt'):  shutil.copy(f'{MODELN}.pt', DATAD)
model     = torch.load(f'{DATAD}/{MODELN}.pt')                                  # 11 s @ /dev/shm
tokenizer = transformers.AutoTokenizer.from_pretrained(f'EleutherAI/{MODELN}')  #  8 s
with torch.cuda.device(0):  model = bminf.wrapper(model)                        # 14 s

pl    = transformers.pipeline('text-generation', model=model, tokenizer=tokenizer, max_length=100, device=0)  # create pipeline
otxts = pl(prompt)
for txt in otxts:
	print(f"\x1b[32m{txt['generated_text']}\x1b[0m")
```

Full error log:

```
/home/da/py38/lib/python3.8/site-packages/torch/nn/modules/module.py:673: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  if param.grad is not None:
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/home/da/.local/lib/python3.8/site-packages/transformers/generation/utils.py:1387: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 50 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Traceback (most recent call last):
  File "./app.py", line 84, in <module>
    txt = pl(prompt)  # inf  # [{'generated_text': 'My Name is philipp k. and I live just outside of Detroit....
  File "/home/da/.local/lib/python3.8/site-packages/transformers/pipelines/text_generation.py", line 202, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/home/da/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1074, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/da/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1081, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/da/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 990, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/da/.local/lib/python3.8/site-packages/transformers/pipelines/text_generation.py", line 244, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/home/da/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/da/.local/lib/python3.8/site-packages/transformers/generation/utils.py", line 1571, in generate
    return self.sample(
  File "/home/da/.local/lib/python3.8/site-packages/transformers/generation/utils.py", line 2534, in sample
    outputs = self(
  File "/home/da/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/da/.local/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 821, in forward
    transformer_outputs = self.transformer(
  File "/home/da/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/da/.local/lib/python3.8/site-packages/transformers/models/gptj/modeling_gptj.py", line 587, in forward
    past_key_values = tuple([None] * len(self.h))
TypeError: object of type 'TransformerBlockList' has no len()
```

**Comment by a710128** [comment]
It looks like bminf.wrapper is not working properly. I'm looking for a solution to this problem.

**Comment by a710128** [comment]
Solved here https://github.com/OpenBMB/BMInf/issues/63
