### ISSUE TITLE
安装成功，但是导入错误

### ISSUE THREAD

**Issue by Mryangkaitong** [OpenBMB/BMTrain#75]
我的环境是cuda11.2，torch 1.12.1+cu113，能够安装成功bmtrain，但是导入错误如下：辛苦请教下这个是什么原因呢？比较急想用BMTrain，辛苦～
import bmtrain
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.8/site-packages/bmtrain/__init__.py", line 16, in <module>
    from . import optim
  File "/root/anaconda3/lib/python3.8/site-packages/bmtrain/optim/__init__.py", line 1, in <module>
    from .adam import AdamOptimizer
  File "/root/anaconda3/lib/python3.8/site-packages/bmtrain/optim/adam.py", line 4, in <module>
    from . import _cuda as C
ImportError: /root/anaconda3/lib/python3.8/site-packages/bmtrain/optim/_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIhEEPT_v

**Comment by Mryangkaitong** [comment]
感谢恢复，还是同意的问题，能够卸载也能狗安装，但是不能导入

**Comment by Mryangkaitong** [comment]
感谢回复，能够卸载，也能狗重新安装，但是还是同样的报错

**Comment by Achazwl** [comment]
what about `pip uninstall bmtrain`, and then `pip install bmtrain --no-cache-dir`
