### ISSUE TITLE
请问单机单卡运行，需要修改什么地方呢？

### ISSUE THREAD

**Issue by qinqinqaq** [OpenBMB/BMTrain#81]

**Comment by qinqinqaq** [comment]
> two options:
> 
> 1. use [distributed launch](https://github.com/OpenBMB/BMTrain#step-4-launch-distributed-training) and set both GPU_PER_NODE and NNODES to 1.
> 2. use normal run such as `python xx.py`, install bmtrain by source code using the latest main branch. The core change is in [de6be9a](https://github.com/OpenBMB/BMTrain/commit/de6be9a902438d0359e524c08df84cdf0291e97b). It is updated after version 0.2.1 released, while version 0.2.2 is not yet ready.

I use option 1:
get some error, Can you give me some advice? Thank you

Traceback (most recent call last):
  File "tune_cpm_ant.py", line 47, in <module>
    tune.run(data)
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 222, in run
    self.forward(train_dataloader, eval_dataloader, cls_num=self.cls_num)
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 122, in forward
    loss = self._forward(train_data, cls_num=cls_num)
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 350, in _forward
    loss = self.loss_function(logits, targets.view(-1))
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/bmtrain/loss/cross_entropy.py", line 200, in forward
    w = (target != self.ignore_index).int()
RuntimeError: CUDA error: no kernel image is available for execution on the device
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16863) of binary: /home/shanhoo3/anaconda3/envs/cpm/bin/python
Traceback (most recent call last):
  File "/home/shanhoo3/anaconda3/envs/cpm/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by qinqinqaq** [comment]
> a=torch.Tensor([1,2])
> a=a.cuda()
> a



> Seems like architecture mismatch, what GPU do you use and what's the cuda version?

but I execute the following code, which is correct

a=torch.Tensor([1,2])
a=a.cuda()
a

**Comment by qinqinqaq** [comment]
> python3 -c "import torch; print(torch.version.cuda)"

cuda:11.3  torch:1.10.1  RTX 3090

**Comment by qinqinqaq** [comment]
> export CUDA_LAUNCH_BLOCKING=1

Still report the same error

====================== Initialization ======================
rank :          0
local_rank :    0
world_size :    1
local_size :    1
master :        shanhoo3:60407
device :        0
cpus :          [0, 1, 2, 3, 4, 5, 6, 7]

root
├── encoder (Encoder)
│   ├── layers (TransformerBlockList)
│   │   ├── 0-0,5-5,7-7,9-9,11-11,16-16,18-18,20-20,24-24,27-27,31-31,36-36,39-40(CheckpointBlock)
│   │   │   ├── self_att (SelfAttentionBlock)
│   │   │   │   ├── layernorm_before_attention (LayerNorm) weight:[4096]
│   │   │   │   └── self_attention (Attention)
│   │   │   │       ├── project_q,project_v(Linear) weight:[8388608]
│   │   │   │       │   └── lora (DistributedLowRankLinear) lora_A:[32768] lora_B:[16384]
│   │   │   │       └── project_k,attention_out(Linear) weight:[8388608]
│   │   │   └── ffn (FFNBlock)
│   │   │       ├── layernorm_before_ffn (LayerNorm) weight:[4096]
│   │   │       └── ffn (FeedForward)
│   │   │           ├── w_in (DenseGatedACT)
│   │   │           │   └── w_0,w_1(Linear) weight:[2867200]
│   │   │           └── w_out (Linear) weight:[2867200]
│   │   ├── 1-2,4-4,6-6,8-8,12-12,23-23,29-30,33-33,42-42(CheckpointBlock)
│   │   │   └── self_att (SelfAttentionBlock)
│   │   │       ├── layernorm_before_attention (LayerNorm) weight:[4096]
│   │   │       └── self_attention (Attention)
│   │   │           ├── project_q,project_v(Linear) weight:[8388608]
│   │   │           │   └── lora (DistributedLowRankLinear) lora_A:[32768] lora_B:[16384]
│   │   │           └── project_k,attention_out(Linear) weight:[8388608]
│   │   └── 17-17,22-22,28-28,37-37,44-45,47-47(CheckpointBlock)
│   │       └── ffn (FFNBlock)
│   │           ├── layernorm_before_ffn (LayerNorm) weight:[4096]
│   │           └── ffn (FeedForward)
│   │               ├── w_in (DenseGatedACT)
│   │               │   └── w_0,w_1(Linear) weight:[2867200]
│   │               └── w_out (Linear) weight:[2867200]
│   └── output_layernorm (LayerNorm) weight:[4096]
├── prompt_embedding (Embedding) weight:[4194304]
├── segment_embedding (Embedding) weight:[131072]
├── input_embedding (Embedding) weight:[125829120]
└── position_bias (SegmentPositionEmbedding) relative_attention_bias:[24576]
[INFO|(OpenDelta)basemodel:696]2023-03-08 14:12:31,772 >> Trainable Ratio: 2457600/1152323584=0.213273%
[INFO|(OpenDelta)basemodel:698]2023-03-08 14:12:31,772 >> Delta Parameter Ratio: 2457600/1152323584=0.213273%
[INFO|(OpenDelta)basemodel:700]2023-03-08 14:12:31,772 >> Static Memory 2.15 GB, Max Memory 2.61 GB
[INFO] Tuning begins...
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.637 seconds.
Prefix dict has been built successfully.
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.409 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "tune_cpm_ant.py", line 47, in <module>
    tune.run(data)
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 222, in run
    self.forward(train_dataloader, eval_dataloader, cls_num=self.cls_num)
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 122, in forward
    loss = self._forward(train_data, cls_num=cls_num)
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 350, in _forward
    loss = self.loss_function(logits, targets.view(-1))
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/bmtrain/loss/cross_entropy.py", line 200, in forward
    w = (target != self.ignore_index).int()
RuntimeError: CUDA error: no kernel image is available for execution on the device
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31822) of binary: /home/shanhoo3/anaconda3/envs/cpm/bin/python
Traceback (most recent call last):
  File "/home/shanhoo3/anaconda3/envs/cpm/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.0', 'console_scripts', 'torchrun')())
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tune_cpm_ant.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-08_14:13:06
  host      : shanhoo3
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 31822)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

run_sh：
#! /bin/bash
export CUDA_LAUNCH_BLOCKING=1
export CUDA_VISIBLE_DEVICES=0
GPUS_PER_NODE=1

NNODES=1
MASTER_ADDR=localhost
MASTER_PORT=12345

OPTS=""
OPTS+=" --dataset-name C3"
OPTS+=" --dataset-path ./dataset/oss_cuge/C3"
OPTS+=" --cls-num 4"
OPTS+=" --output-path ./output/C3"
OPTS+=" --model-path ./pretrain_models/cpm_live_1b/cpm-ant-1b.pt"
OPTS+=" --config-path ./pretrain_models/cpm_live_1b/cpm-ant-1b.json"
OPTS+=" --batch-size 4"
OPTS+=" --early-stop-patience 10"
OPTS+=" --eval-interval 50"
OPTS+=" --tune-maxlen 1024"
OPTS+=" --lr 1e-3"
OPTS+=" --warmup-iters 50"
OPTS+=" --epochs 20"

TUNE_CMD="torchrun --nnodes=${NNODES} --nproc_per_node=${GPUS_PER_NODE} --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_ADDR}:${MASTER_PORT} tune_cpm_ant.py ${OPTS}"
#TUNE_CMD="python3 tune_cpm_ant.py ${OPTS}"

echo ${TUNE_CMD}
$TUNE_CMD

INFER_CMD="python -u infer_cpm_ant.py ${OPTS}"
echo ${INFER_CMD}
$INFER_CMD

**Comment by qinqinqaq** [comment]
> Sorry, I mean
> 
> ```
> print(target.dtype, target.device, target.shape)
> ```
print(target.dtype, target.device, target.shape)
torch.int64 cuda:0 torch.Size([32])

**Comment by qinqinqaq** [comment]
> Try the following code
> 
> ```
> import torch
> target = (torch.rand((32,))*100000).to(torch.int64).cuda()
> print(target.dtype, target.device, target.shape)
> ret = (target != -100).int()
> print(target, ret)
> ```
No problem with that

torch.int64 cuda:0 torch.Size([32])
tensor([10774, 12657, 33614, 78932, 97760, 75976, 96933, 25522, 62390, 51455,
        27301, 15220, 78448, 33771, 29875, 97263, 66820, 69208, 74462, 62388,
        73307, 45559, 32449,    34, 42047, 41038, 92167, 11860, 42870, 87416,
        33985, 80742], device='cuda:0') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0', dtype=torch.int32)

**Comment by qinqinqaq** [comment]
> Since I can run in the same environment setting, it's hard to debug. Whether or not your `nvcc --version` match your torch cuda version?
Can I execute the following code, theoretically the CUDA version matches Torch, right?

>>> import torch
>>> a = torch.tensor([0]).cuda()
>>> a
tensor([0], device='cuda:0')

**Comment by qinqinqaq** [comment]
> Hard to figure out why. From your log, it seems that the forward of BMTrain model has successfully passed, the error is on the loss function. I tried the following code using the same environment as yours but raise no error.
> 
> ```python
> import torch
> import bmtrain as bmt
> 
> bmt.init_distributed()
> 
> loss_func = bmt.loss.FusedCrossEntropy()
> input = torch.randn(32, 100).half().cuda()
> input.requires_grad_(True)
> target = torch.randint(0, 100, (32,)).long().cuda()
> loss = loss_func(input, target)
> loss.backward()
> ```
> 
> Could you help me modify the file `/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/bmtrain/loss/cross_entropy.py`, add
> 
> ```python
> print(w.dtype, w.device, w.shape)
> print(self.ignore_index)
> ```
> 
> before the line `w = (target != self.ignore_index).int()`, and tell me the printed result.
> 
> > File "/home/shanhoo3/anaconda3/envs/cpm/lib/python3.8/site-packages/bmtrain/loss/cross_entropy.py", line 200, in forward
> > w = (target != self.ignore_index).int()

Hello, are you executing this code on torchrun?

**Comment by qinqinqaq** [comment]
> using `torchrun --nnodes=1 --nproc_per_node=1 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:12345 test.py`
> 
> enviroment:
> 
> * `nvcc --version`
>   ```shell
>   nvcc: NVIDIA (R) Cuda compiler driver
>   Copyright (c) 2005-2021 NVIDIA Corporation
>   Built on Sun_Mar_21_19:15:46_PDT_2021
>   Cuda compilation tools, release 11.3, V11.3.58
>   Build cuda_11.3.r11.3/compiler.29745058_0
>   ```
> * `torch.__version__` is `1.10.2+cu113`
> * gpu `GeForce RTX 3090`

When I debug, I find a particularly interesting thing, the first execution in the terminal generates an error, and the second execution of the same code succeeds.

Do you know what caused this? Or how to fix it?

(target != self.ignore_index).int()
Traceback (most recent call last):
  File "/home/shanhoo3/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(target != self.ignore_index).int()
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0', dtype=torch.int32)

> using `torchrun --nnodes=1 --nproc_per_node=1 --rdzv_id=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:12345 test.py`
> 
> enviroment:
> 
> * `nvcc --version`
>   ```shell
>   nvcc: NVIDIA (R) Cuda compiler driver
>   Copyright (c) 2005-2021 NVIDIA Corporation
>   Built on Sun_Mar_21_19:15:46_PDT_2021
>   Cuda compilation tools, release 11.3, V11.3.58
>   Build cuda_11.3.r11.3/compiler.29745058_0
>   ```
> * `torch.__version__` is `1.10.2+cu113`
> * gpu `GeForce RTX 3090`
